name: Build and Release APK

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Enter release title"
        required: true

env:
  main_project_module: app
  playstore_name: Kuizu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build gradle project
        run: ./gradlew build

      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleRelease

      # Rename the APK file before uploading
      - name: Rename APK to Kuizu.apk
        run: mv ${{ env.main_project_module }}/build/outputs/apk/release/app-release.apk ./Kuizu.apk

      # Create Release and Upload Renamed APK to GitHub Release
      - name: Create and Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./Kuizu.apk"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_RELEASE }}
